title: Christopher Lindsay
base_url: https://christopher-lindsay.github.io
cv: /assets/Lindsay_CV.pdf
twitter: https://twitter.com/chris_j_lindsay
ads: https://ui.adsabs.harvard.edu/public-libraries/VaWdqEevQryfunHxj862jg
tedx: https://www.youtube.com/watch?v=un5529ZmC_4
instagram: https://www.instagram.com/dontdischris/
logo: /assets/img/Dogs2.jpg
description: Christopher Lindsay
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
